project_id = "rxehpdmcwfxkabrnwhoi"

[functions.send-status-email]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.create-first-admin]
verify_jwt = false

[functions.notify-project-submitted]
verify_jwt = false

[functions.customer-portfolio-api]
verify_jwt = false
