project_id = "rxehpdmcwfxkabrnwhoi"

[functions.send-status-email]
verify_jwt = false

[functions.manage-users]
verify_jwt = false

[functions.create-first-admin]
verify_jwt = false

[functions.notify-project-submitted]
verify_jwt = false

[functions.customer-portfolio-api]
verify_jwt = false

[functions.import-estoque]
verify_jwt = false

[functions.generate-project-summary]
verify_jwt = false

[functions.orcamento-chat]
verify_jwt = false

[functions.generate-visit-pdf]
verify_jwt = false

[functions.send-visit-report]
verify_jwt = false
